// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    return $(".tabs a").on("click", function(e) {
      var target;
      e.preventDefault();
      target = $(this).attr('href');
      $(".tab", $(this).closest(".tabs")).removeClass("active");
      $(this).closest(".tab").addClass("active");
      $(".panel").hide;
      $(target).fadeIn("slow");
    });
  });

}).call(this);
